services:
  - type: web
    name: katrin-f-art-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PUBLIC_URL
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
      - key: BEHANCE_URL
        sync: false
